FROM python:3.7.0-slim-stretch

# for debuuging and testing temporarily we can install packages below
RUN apt-get update && apt-get install -y net-tools iputils-ping nmap


RUN mkdir -p /opt/gobgp_control
WORKDIR /opt/gobgp_control/

RUN pip install grpcio grpcio-tools googleapis-common-protos jupyter

# Copy compiled gRPC python files for controller
COPY control/* ./
COPY proto_files/* ./

# Add Tini. Tini operates as a process subreaper for jupyter. This prevents
# kernel crashes.
#ENV TINI_VERSION v0.6.0
#ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
#RUN chmod +x /usr/bin/tini
#ENTRYPOINT ["/usr/bin/tini", "--"]

# Run Jupyter Notebook
RUN mkdir -p /root/.jupyter
COPY configs/jupyter_notebook_config.py /root/.jupyter/
#CMD ["jupyter", "notebook", "--port=8080", "--ip=0.0.0.0", "--allow-root"]

EXPOSE 8080

#ENTRYPOINT ["sleep", "9999999"]
ENTRYPOINT ["jupyter", "notebook", "--port=8080", "--ip=0.0.0.0", "--allow-root"]
